// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djrjuahekayhktqhapdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqcmp1YWhla2F5aGt0cWhhcGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTYzNTQsImV4cCI6MjA2NTc5MjM1NH0.DHFCX50nQ-Mjno-Q6QetZpEuYFbWalELlGika1kbSsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);